#------------------------------------------------------------------------------
# Makefile
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

all:

install:
	install -d $(PREFIX)/bin
	install -m 755 run_fillminima.py $(PREFIX)/bin
	install -m 664 fillminima.py $(PREFIX)/bin

clean:

