#------------------------------------------------------------------------------
# Makefile
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

all:

install:
	install -d $(PREFIX)/bin
	install -m 775 cfmask.py $(PREFIX)/bin

clean:


